blank_issues_enabled: false
contact_links:
  - name: MARiS GitHub Org Discussions
    url: https://github.com/orgs/UCT-MARiS/discussions
    about: General code discussions within the ARU GitHub Org.
  - name: MARiS Website
    url: https://maris.uct.ac.za
    about: The ARU website.
